language: node_js
node_js:
  - '6'
  - '7'
  - '8'
cache: yarn
script:
  - git config core.safecrlf true
  - git config core.autocrlf input
  - git config -l
  - npm run precommit
    # get the coverage metrics to coveralls
  - cat coverage/typescript/lcov.info | ./node_modules/coveralls/bin/coveralls.js
